- name: "Set variables"
  set_fact:
    database: "{{ database_item.db }}"

- name: "Create database"
  postgresql_db:
    name: "{{ database_item.db }}"
    encoding: "{{ database_item.encoding | default(omit) }}"
  become: yes
  become_user: postgres

- name: "Configure users"
  include_tasks: users.yml
  vars:
    userdb: "{{ database }}"
  with_items:
    - "{{ database_item.users }}"
  loop_control:
    loop_var: user_item
  when:
    - database_item.users is defined
    - database_item.users is not string
    - database_item.users is not mapping
    - database_item.users is iterable
    - database_item.users | length > 0
  no_log: True
