- name: "Create database"
  postgresql_db:
    name: "{{ item.name }}"
  become: yes
  become_user: postgres
- name: "Create db user"
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
  become: yes
  become_user: postgres
- name: "Grant db user access to app db"
  postgresql_privs:
    type: schema
    db: "{{ item.name }}"
    obj: public
    state: present
    roles: "{{ item.user }}"
    privs: "{{ item.priv }}"
    grant_option: no
  become: yes
  become_user: postgres
